apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"pod-design-app","skaffold.dev/run-id":"f59103ca-a5f0-4fb8-aa3b-9e60e4bfe37a"},"name":"poddesigndeployment","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"pod-design-app"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"pod-design-app","skaffold.dev/run-id":"f59103ca-a5f0-4fb8-aa3b-9e60e4bfe37a"}},"spec":{"containers":[{"image":"poddesign-0.0.1-snapshot.jar:3c979d090752f7a98aafeb2667722d41cb265166b8742694ee783894c46aba75","name":"pod-design-app","ports":[{"containerPort":8081}]}]}}}}
  creationTimestamp: "2021-10-24T17:13:55Z"
  generation: 2
  labels:
    app: pod-design-app
    skaffold.dev/run-id: f59103ca-a5f0-4fb8-aa3b-9e60e4bfe37a
  name: poddesigndeployment
  namespace: default
  resourceVersion: "95933"
  uid: ca7655eb-2bea-4b02-8c68-6f41f751ef00
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pod-design-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pod-design-app
        skaffold.dev/run-id: f59103ca-a5f0-4fb8-aa3b-9e60e4bfe37a
    spec:
      containers:
      - image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        name: pod-design-app
        ports:
        - containerPort: 8081
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2021-10-24T17:13:58Z"
    lastUpdateTime: "2021-10-24T17:13:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-10-24T17:13:55Z"
    lastUpdateTime: "2021-10-24T17:15:44Z"
    message: ReplicaSet "poddesigndeployment-698cd49cc6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
