apiVersion: apps/v1
kind: Deployment
metadata:
  name: poddesigndeployment
  labels:
    app: pod-design-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-design-app
  template:
    metadata:
      labels:
        app: pod-design-app
    spec:
      containers:
        - name: pod-design-app
          image: poddesign-0.0.1-SNAPSHOT.jar
          ports:
            - containerPort: 8081