apiVersion: v1
kind: Service
metadata:
  name: poddesignservice
  labels:
    name: podservice
spec:
  selector:
    app: pod-design-app
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30009
  type: LoadBalancer